### ISSUE TITLE
Unexpected behavior while merging 2 objects into an empty object

### ISSUE THREAD

**Issue by subhranshudas** [KyleAMathews/deepmerge#101]
Hi ,
Was trying to merge two deeply nested objects into another empty object.
I get the unexpected behavior as follows. Any inputs as to why?
https://repl.it/repls/GloriousRepentantUnix
The reason i want to merge to an empty object is i don't want to mutate the original objects.
Thanks.

**Comment by TehShrike** [comment]
The merge function only takes two objects, not three: https://github.com/KyleAMathews/deepmerge#mergex-y-options

In your first example the third `target` argument is interpreted as the options object.

Like the docs say, "Merging creates a new object, so that neither x or y are be modified."

If you wanted deepmerge to mutate the target object, you would have to pass in the [`clone: false` option](https://github.com/KyleAMathews/deepmerge#clone).  (That option is deprecated.)

If you want to pass in more than two objects to be merged, you should call [`merge.all`](https://github.com/KyleAMathews/deepmerge#mergeallarrayofobjects-options).
