### ISSUE TITLE
Feature - Overlay option

### ISSUE THREAD

**Issue by tallreddad** [KyleAMathews/deepmerge#110]
I have a use case where I want to overlay one object on another instead of merging the 2 objects into a 3rd new object. I made a modification to deepmerge to accept an "overlay" option which will cause properties to be copied to the target object instead of creating a new destination object. After this change it satisfies my use case. Is this something that would be helpful to contribute to the project?

**Comment by TehShrike** [comment]
Does setting `clone` to `false` meet your use case? https://github.com/KyleAMathews/deepmerge#clone

**Comment by TehShrike** [comment]
Yeah, that `clone` behavior exists because the original versions of deepmerge would always create a new target object, but wouldn't create new objects for any properties.

It was confusing and wrong.

I've been leaning towards pushing deepmerge in a "always clone, all the time" direction.

Depending on your needs, [`assign-deep`](https://github.com/jonschlinkert/assign-deep) may work for you?

**Comment by tallreddad** [comment]
Ah! Yes, assign-deep directed me to lodash's _.merge which did the trick. Thank you!
