### ISSUE TITLE
Make a check for string first, overwrite strings.

### ISSUE THREAD

**Issue by mesqueeb** [KyleAMathews/deepmerge#114]
I have an object with lots of props, some of them are objects, some string.
I am looping over each key to see if it already exists on another object.
if it does, i'm merging the value of those props.
**however, this is sometimes not an object but a string!**

With merge() if I try `merge('ab', 'ba')` I end up with an object: `{0: 'b', 1: 'a'}`.

Maybe deepmerge can first check if it's really an object, and if it's strings just return the last string?

my snippet:
```
return Object.keys(doc).forEach(key => {
          // Merge if exists
          const newVal = (state[key])
            ? merge(state[key], doc[key], {arrayMerge: overwriteMerge})
            : doc[key]
          this._vm.$set(state, key, newVal)
        })
```

**Comment by macdja38** [comment]
I'm not sure this warrants a special case, potentially it might make more sense to either wrap deep merge in your code or simply check if it's a string before merging. If anything deep merge should probably throw an error, it was never designed to work on strings, and doesn't really have a valid way of *merging* strings.

Let me know your thoughts on why this should be built into the library and in what cases this would be the expected behaviour.

**Comment by mesqueeb** [comment]
A custom wrapper is a good idea. I implemented my own logic.
I agree we should not bloat the package with such specific use cases.
