### ISSUE TITLE
typescript type definition is wrong

### ISSUE THREAD

**Issue by nataly87s** [KyleAMathews/deepmerge#120]
this code:
```
import * as deepmerge from 'deepmerge';

const obj1 = {a:'a'};
const obj2 = {b:'b'};
const merge = deepmerge(obj1, obj2);
```

causes this error:
`Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/.../node_modules/deepmerge/index")' has no compatible call signatures.`

the type definition in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/deepmerge) seems to be correct.
the difference is that index.d.ts has a default export, but the code doesn't really have one

**Comment by nataly87s** [comment]
It's not a lot of code, you can rewrite it to TypeScript. I can do it if you want

**Comment by TehShrike** [comment]
No worries, I'm writing a quick and dirty one in another branch.

**Comment by TehShrike** [comment]
Fixed by #121, released as 2.2.1

**Comment by msssk** [comment]
It occurs to me there may be some inconsistency in TS development environments, so I'm going to do some more testing. Looking at the issues in this project you can see that multiple people found the DefinitelyTyped typedefs to be broken - broken in the sense that they didn't work with any reasonable syntax (neither `import merge from 'deepmerge'` nor `import * as merge from 'deepmerge'`). The typedefs I submitted work for me in practice without problem (`import merge from 'deepmerge'`); however, I've only tested so far in my current project, which is Gatsby (which uses Webpack and Babel 7; Babel 7 added its own TS support so I don't think my code is even going through the official TS compiler).

I'll test in a pure TS project with the `tsc` compiler and see what happens. I do think that pure TS is what should be supported, but it's a shame if Webpack and/or Babel are breaking things so that it appears the typedefs are broken.

**Comment by TehShrike** [comment]
@msssk the problem described in those other issues has to do with Webpack, not TypeScript.  I will update the issue description to make it accurate.  The Webpack issue in question is https://github.com/webpack/webpack/issues/6584

**Comment by MatissJanis** [comment]
I'm having problems with v2.2.1. Downgrading to v2.2.0 fixes the issue (I'm using the 2nd syntax from the examples below).

```typescript
import * as merge from 'deepmerge';
console.log(merge); // Object{default: function deepmerge(target, source, options) { ... }}
// No Typescript error, but code is broken since `merge` is not a function
```
```typescript
import merge from 'deepmerge';
console.log(merge); // function deepmerge(target, source, options) { ... }
// Typescript error: error TS1192: Module '".../node_modules/deepmerge/index"' has no default export.
```

**Comment by nataly87s** [comment]
If you add `esModuleInterop = true` to tsconfig the first syntax works

You can also use `const merge = require('deepmerge')`

**Comment by MatissJanis** [comment]
It's not a great experience to require devs manually setting a TS config flag for this package to work, but either way - thanks for the fast reply.

**Comment by luiscla27** [comment]
I've just noticed this issue by reviewing changes done to index.d.ts file due to issue #130, @nataly87s, @TehShrike the `export = deepmerge;` implementation is deprecated, the correct way to fix this is upgrading your angular version to at least 6.2.1.

Please please please revert this :D

**Comment by nataly87s** [comment]
I'm not using angular...

**Comment by nataly87s** [comment]
@luiscla27 the type definition said there's a default export, but the code itself didn't actually have it. This is a TypeScript issue, this package is not only for angular

**Comment by nataly87s** [comment]
@luiscla27 if you look at your pr, you can see that the TypeScript tests are not passing

**Comment by luiscla27** [comment]
That's because @TehShrike added a test specially to reject the 'export default' implementation, so you are saying angular devs should stay on version 2.1.1??

We've stayed at version 2.1.1 because our project broke at 2.2.0... today i've finally checked why and it was because of this :S

@nataly87s can you please add a demo project of your issue so maybe i can help with a solution that works for you and also angular devs?

**Comment by nataly87s** [comment]
@luiscla27 it's used here https://github.com/Soluto/shisell-js/blob/master/src/internal/AnalyticsContext.ts

**Comment by luiscla27** [comment]
Thank you, by know we'll stay at 2.1.1

**Comment by TehShrike** [comment]
As of 3.0.0, there is no ES Module export any more.  This should prevent any of this confusion.  All hail Webpack, the broken bundler that everyone uses!

There were no other changes between 2.2.1 and 3.0.0, so everyone should be able to immediately upgrade to deepmerge@3 and not have import/require issues any more.  The TypeScript definition is correct with 3.0.0, no matter what bundler you're using.

Either of these should work, even with Webpack, even as a transitive dependency:

```js
import * as deepmerge from 'deepmerge'
const deepmerge = require('deepmerge')
```

**Comment by patricknazar** [comment]
For version 4 I had to use `const deepmerge = require('deepmerge')` for it to work with jest tests. The `import * as deepmerge from 'deepmerge'` style gave me the lack call signature error. I don't know why, wish I did.
