### ISSUE TITLE
marge fails if an array is merged with object {key : val1}, {key : val2}

### ISSUE THREAD

**Issue by totalcloudio** [KyleAMathews/deepmerge#45]
To reproduce : 

var merge = require('deepmerge');
var c = [
    {
      delta:"A"
    }
];

var d = [
  {
    delta:"C"
  }
];

console.log(merge(c,d));

required === [ { delta: 'A' }, { delta: 'C' } ]
got === [ { delta: 'C' } ]

npm : 2.7.6
node : v4.4.3

**Comment by TehShrike** [comment]
That's actually expected behavior - [this test](https://github.com/KyleAMathews/deepmerge/blob/ef1c6bac8350ba12a24966f0bc7da02560827586/test/merge.js#L206-L221) asserts it.

I agree it's a bit confusing that non-identical primitive values are appended, while non-identical objects are merged.

We may eventually include some other array merging algorithms that might make more sense for people, but for backwards-compatability's sake, we'll probably keep defaulting to the current function.  In the mean-time, your best bet is to define a custom array merging function that does what you want.

See the [options](https://github.com/KyleAMathews/deepmerge#mergex-y-options) argument for details.
