### ISSUE TITLE
Passing arguments by reference

### ISSUE THREAD

**Issue by monolithed** [KyleAMathews/deepmerge#55]
### Actual

```js
options = deepmerge(options, { y: true });
options // {y: true}
```

#### Real example

```js
module.exports = (options = {}) => {
	options = deepmerge({
		cache: true,
		format: 'node_modules/eslint-friendly-formatter',
		fix: true,
		extensions: ['.js']
	}, options);
```
 
`options, options, options`, so ugly ))

### Expected

```js
deepmerge(options, { y: true }, { reference: true });
options // {y: true}
```

It's just a proposal

**Comment by TehShrike** [comment]
This is a bit tricky since one of `deepmerge`'s original features is "always return a new object".

If the [clone](https://github.com/KyleAMathews/deepmerge#clone) option had existed from the beginning, it have probably affected the root objects in addition to all of their children.

This feels like a feature creep too far for me, though I'm open to other opinions.
