### ISSUE TITLE
merge.all with single element array

### ISSUE THREAD

**Issue by shawn98ag** [KyleAMathews/deepmerge#71]
I'm curious why when one calls `merge.all()` with a single element array, `[{'a':1}]`, this function doesnt just return the value of that first element in the array `{'a':1}`? The function is instead throwing an error.

In my code, I'm dynamically creating an array of objects that I need to merge together. Occasionally, that array only has one element. To protect against this error I have to add `.concat({})` to the array argument increase its length to 2.

**Comment by TehShrike** [comment]
deepmerge doesn't mutate either argument that is passed in to it, so it's difficult to imagine what would happen if you passed just a single object to it.  Would it just be a shallow copy to a new object, like `Object.assign`?

It would be a breaking change, but I think it would be a bit easier to fix this if we made `clone` default to `true` so that there would always be some default behavior you could expect ("copy everything").

As an aside, I'd personally prefer this to the concat I think:
```js
const output = array.length > 1 ? merge.all(array) : array[0]
```
Or if you want the copy:
```js
const output = array.length > 1 ? merge.all(array) : merge({}, array[0])
```

**Comment by TehShrike** [comment]
My current stance: if we do publish a breaking change to make cloning the default (#72), we can feel free to make this change so that `merge.all` can take any number of inputs.

**Comment by TehShrike** [comment]
As of version 2.0.0, `merge.all` takes an array of any size, including 0.
