### ISSUE TITLE
Does `clone: false` need to be deprecated?

### ISSUE THREAD

**Issue by lowerends** [KyleAMathews/deepmerge#86]
I noticed that cloning a javascript `class` using the default deepmerge converts that class to a regular object, thereby loosing its functionality. Merging it with `{clone: false}` keeps the class, and thus its functionality, intact. 

Therefor my question: will the  `{clone: false}` option really be deprecated?

**Comment by TehShrike** [comment]
I think it should be, yes.

The `clone` object doesn't work like you'd expect when set to false, for backwards compatibility reasons, and that is confusing.

From the beginning, this module was written to *always* create a new root object to copy properties onto, but all child objects were copied straight over.

Then, [the `clone` option was added](https://github.com/KyleAMathews/deepmerge/issues/28) so that users could have the more consistent behavior of every object being created new in the target object tree.  The root object was still always cloned onto a new object.

You can see the behavior [in this jsfiddle](https://jsfiddle.net/urqh1v0x/1/) - even when `clone` is false, the root object is still created new.  If your class-based object is the root object that you are merging, then that class is lost during the merge, even when `clone` is false.

This is confusing and I think it is preferable to just clone everything all the time.

Another option would be to change it so that the root object would not be cloned when `clone` was false.  This would be a breaking change, but it would also force us to revisit what should happen [when `deepmerge.all` is called with zero or one elements in the array with `{ clone: false }`](https://github.com/KyleAMathews/deepmerge/issues/71).

The `clone: false` behavior is poorly implemented for backwards compatibility reasons, would be difficult to fix without breaking `all`, and I think it should go away.

**Comment by lowerends** [comment]
Ok, that makes sense.
Thanks for your detailed explanation.
