### ISSUE TITLE
Ability to set default options

### ISSUE THREAD

**Issue by adamreisnz** [KyleAMathews/deepmerge#89]
Would you be open for a PR where we can specify the default options globally?

My `arrayMerge` strategy is to always overwrite the array instead of concatenating, so it's quite annoying to have to specify the options with the overwrite function every time I use deepmerge across various files, and it has already caused some annoying bugs.

Example:

```js
const merge = require('deepmerge');
merge.setDefaultOptions({
  arrayMerge: (dest, source) => source,
});
```

Afterwards, every merge would use those options as the default, unless specific options are passed in.
Happy to create a PR for it.

**Comment by macdja38** [comment]
hmm. it wouldn't be a good idea to have that change the global deepmerge that's being required, so it would probably be best if menge.setDefaultOptions returns a copy of merge that can be used instead... something like
```js
const merge = require('deepmerge').setDefaultOptions({
  arrayMerge: (dest, source) => source,
});
```

Otherwise two libraries in the same application that use deepmerge could interfere.

**Comment by adamreisnz** [comment]
Yes, I was planning to make it chainable and return a copy of merge

**Comment by TehShrike** [comment]
Either way, you still have to do the same thing in your project - which is make a `merge.js` file in your shared/common folder for everything in your project to import.

I'm hesitant to add new code to this project, since setting defaults on your own is so easy to do, and there are even different flavors you might want to expose internally.

Able to override options:

```js
import arrayMerge from './somewhere'
import deepmerge from 'deepmerge'
export default (a, b, options) => deepmerge(a, b, Object.assign({ arrayMerge }, options))
```

Unable to override options:

```js
import arrayMerge from './somewhere'
import deepmerge from 'deepmerge'
export default (a, b) => deepmerge(a, b, { arrayMerge })
```

Able to merge any number of objects:

```js
import arrayMerge from './somewhere'
import deepmerge from 'deepmerge'
export default (...objects) => deepmerge.all(objects, { arrayMerge })
```

I think it's better to let everyone decide how they want `merge` to be exposed to their project with a line of JS instead of using a baked-in extend function on the library.

**Comment by adamreisnz** [comment]
@TehShrike no, that's incorrect. I am using ES6 and standard `require`'s, as I imagine the majority of people using Node still do.

As such, all `require`'s are cached, so I can simply set the defaults once, in my initialisation file, and then whenever I require `deepmerge` elsewhere in my application I won't have to worry about the defaults.

E.g.:

init.js
```js
//Set default merge options for deep merge
require('deepmerge').setDefaultOptions({
  arrayMerge: (dest, source) => source,
});
```

anywhere-else.js
```js
const merge = require('deepmerge');
merge(a, b); //Will use the defaults as defined earlier.
```

**Comment by TehShrike** [comment]
Yes, that's what @macdja38 was addressing - that syntax also affects any other modules that you're requiring.  If you're using some gulp library or whatever that uses `deepmerge`, you don't want to mess with its default properties.

Your usage of `deepmerge` shouldn't affect some webpack library that also happens to use `deepmerge`.

Ignore the ES Module syntax in my previous response.  The problems are exactly the same even if I use CommonJS in the examples.

**Comment by adamreisnz** [comment]
Gotcha, fair point, although I'm using the library in an isolated
environment server side.

I'll just make my own wrapper then with my defaults in there.
